version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: jemz_arena_db
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: jemz_arena
    ports:
      - '5435:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
